language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # FLTK
  - sudo apt-get install libfltk1.3-dev

services:
  - xvfb

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_fltk &
  - sleep 10
  - sudo killall travis_qmake_gcc_cpp14_fltk
